# Generated by Django 2.2.1 on 2019-05-12 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('acc', models.FloatField(default=0)),
                ('loss', models.FloatField(default=1000)),
                ('target_epoches', models.IntegerField(default=0)),
                ('now_epoches', models.IntegerField(default=0)),
                ('lr', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ValidateImageTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='image_classification/')),
                ('save_to_db', models.BooleanField(default=False)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_classification.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='image_classification/')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_classification.Classification')),
            ],
        ),
        migrations.AddField(
            model_name='classification',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_classification.Dataset'),
        ),
    ]
